<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-21 at 12:06:02.
 */
class filesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var files
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new files;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers files::getFileName
     * @todo   Implement testGetFileName().
     */
    public function testGetFileName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
