<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-21 at 12:09:26.
 */
class supportTest extends PHPUnit_Framework_TestCase {

    /**
     * @var support
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new support;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
