<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-21 at 12:06:13.
 */
class userTest extends PHPUnit_Framework_TestCase {

    /**
     * @var user
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new user;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers user::getNom
     * @todo   Implement testGetNom().
     */
    public function testGetNom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user::getPrenom
     * @todo   Implement testGetPrenom().
     */
    public function testGetPrenom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user::getMail
     * @todo   Implement testGetMail().
     */
    public function testGetMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
